name: Update Countdown Circle

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install pillow
      - run: python timer_generator.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update countdown image"
          add: 'countdown.png'
          push: --force
